import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import { dir } from "i18next";
import i18nConfig from "../i18n/i18nConfig";

// 静态生成路由
export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale} dir={dir(locale)} data-theme='winter'>
      <body>{children}</body>
    </html>
  );
}
